---
title: Steve Annis
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: false
  music-videos:
    title: Music Videos
    output: true
  commercials:
    title: Commercials
    output: true
defaults:
url: https://www.steveannisdop.com
description: Award-winning Director of Photography
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
email: hello@steveannisdop.com
job: Director of Photography
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %Y"
future: true
social: 
 instagram: https://www.instagram.com/steveannisdop/
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title â€” :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
imgix:
  source: steveannis.imgix.net